<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Practice_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr=np.random.randint(0,100,10)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())

[34 18 25 37 84 95 84  1 26 99]
99
1
50.3


In [11]:
arr2= np.array([45, 60, 55, 30, 90, 75, 40, 50])
print(arr2)
print(arr2[arr2>50])
print(np.sort(arr2))
print(np.argmax(arr2))

[45 60 55 30 90 75 40 50]
[60 55 90 75]
[30 40 45 50 55 60 75 90]
4


In [21]:
temp=np.random.randint(20,40,(4,4))
print(temp)
print(np.mean(temp,axis=1)) #if row axis=1,col axis=0
print(np.max(temp))
temp[temp>35]=35
print(temp)


[[24 37 31 32]
 [37 30 20 37]
 [27 22 28 23]
 [22 28 26 23]]
[31.   31.   25.   24.75]
37
[[24 35 31 32]
 [35 30 20 35]
 [27 22 28 23]
 [22 28 26 23]]


In [23]:
traffic=np.random.randint(0,50,(3,5))
print(traffic)
print(np.sum(traffic,axis=0))
print(np.sum(traffic,axis=1))

[[11 33  5 20  2]
 [49 48 28 24 49]
 [17 11 27 39 35]]
[77 92 60 83 86]
[ 71 198 129]


In [30]:
stock = np.array([12, 15, 9, 20, 18])
new_delivery=stock+5
print(new_delivery)
spoiled=new_delivery*0.10
print(spoiled)
final_stock=new_delivery-spoiled
print(final_stock)

[17 20 14 25 23]
[1.7 2.  1.4 2.5 2.3]
[15.3 18.  12.6 22.5 20.7]


# Pandas Practice

In [45]:
import pandas as pd

data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
 }
df = pd.DataFrame(data)
print(df)
print( df.columns)
print( df.index)

     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85
3   Babul    60       70       65
4    Mitu    80       88       90
Index(['Name', 'Math', 'English', 'Science'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


In [35]:
df.head(3)

Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85

In [52]:
data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
 }
df = pd.DataFrame(data)

print(df[['Product', 'Price']])


   Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50


In [53]:
print(df.iloc[2])   # using position
print(df.loc[2])    # using label


Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object
Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object


In [55]:
df['Revenue']=df['Price']*df['Units_Sold']
top3=df.sort_values(by='Revenue',ascending=False).head(3)
print(top3[['Product','Revenue']])

  Product  Revenue
0   Phone     7000
1  Laptop     6000
2  Tablet     2400


3.Attendance Tracker
Here’s an attendance sheet:

 data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Make 'Student' the index column.
 2. Drop the 'Days_Absent' column

In [56]:
import pandas as pd

data = {
    'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
    'Days_Present': [20, 18, 22, 15, 25],
    'Days_Absent': [2, 4, 1, 7, 0]
}

df = pd.DataFrame(data)

In [57]:
df=df.set_index('Student')
print(df)

         Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0


In [58]:
df.drop('Days_Absent',axis=1)
print(df)

         Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0


4. Filtering Employee Data
Employee record:

 data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show employees with Salary > 45000.
 2. Show employees from the IT department only.
 3. Show employees with Salary > 45000 and Experience > 3.
 4. Sort the employees by Experience (ascending).


In [60]:
data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
df = pd.DataFrame(data)


In [61]:
highest_sal=df[df['Salary']>45000]
print(highest_sal)

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6


In [63]:
it_dept=df[df['Department']=='IT']
print(it_dept)

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4


In [64]:
salary_and_exp=df[(df['Salary']>45000)& (df['Experience']>3)]
print(salary_and_exp)

    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6
