<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Practice_3_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arr=np.random.randint(0,100,10)
print(arr)
print(arr.max())
print(arr.min())
print(arr.mean())

[34 18 25 37 84 95 84  1 26 99]
99
1
50.3


In [11]:
arr2= np.array([45, 60, 55, 30, 90, 75, 40, 50])
print(arr2)
print(arr2[arr2>50])
print(np.sort(arr2))
print(np.argmax(arr2))

[45 60 55 30 90 75 40 50]
[60 55 90 75]
[30 40 45 50 55 60 75 90]
4


In [21]:
temp=np.random.randint(20,40,(4,4))
print(temp)
print(np.mean(temp,axis=1)) #if row axis=1,col axis=0
print(np.max(temp))
temp[temp>35]=35
print(temp)


[[24 37 31 32]
 [37 30 20 37]
 [27 22 28 23]
 [22 28 26 23]]
[31.   31.   25.   24.75]
37
[[24 35 31 32]
 [35 30 20 35]
 [27 22 28 23]
 [22 28 26 23]]


In [23]:
traffic=np.random.randint(0,50,(3,5))
print(traffic)
print(np.sum(traffic,axis=0))
print(np.sum(traffic,axis=1))

[[11 33  5 20  2]
 [49 48 28 24 49]
 [17 11 27 39 35]]
[77 92 60 83 86]
[ 71 198 129]


In [30]:
stock = np.array([12, 15, 9, 20, 18])
new_delivery=stock+5
print(new_delivery)
spoiled=new_delivery*0.10
print(spoiled)
final_stock=new_delivery-spoiled
print(final_stock)

[17 20 14 25 23]
[1.7 2.  1.4 2.5 2.3]
[15.3 18.  12.6 22.5 20.7]
