<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Shore_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
arr=[1,2,3]
print(arr*5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [2]:
arr=[x*5 for x in arr]
print(arr)

[5, 10, 15]


In [15]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

# **Array Attributes**

In [17]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


In [18]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [19]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


***selecting a data type for an array***

In [26]:

arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int64
int16


**nd array creation from existing data**

In [31]:
lst=[12,45,60.44,98,"tehe"]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

['12' '45' '60.44' '98' 'tehe']
<class 'numpy.ndarray'>
<U32


In [32]:
tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [37]:
st={1,2,4}
# Convert the set to a list before creating the numpy array
arr = np.array(list(st),dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[1 2 4]
<class 'numpy.ndarray'>
int16
(3,)
1


In [41]:
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr1=np.array(list(values))
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

arrt=np.array(list(items))
print(arrt)
print(type(arrt))
print(arrt.dtype)
print(arrt.shape)
print(arrt.ndim)
print(arrt.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6
