<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Shore_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

arr=np.random.randint(1,100,size=(10,5)) #sample 10,feature 5

arr.shape
print(arr)

[[43 28 56 19 29]
 [90 14 81 57 44]
 [74 16 11  2 64]
 [22 57 13 75 93]
 [ 7 93 36  5 24]
 [11 99 46  3 23]
 [74 58 33 64 93]
 [16 37 92 84 43]
 [20 33 53  6 46]
 [27 76 83 31 67]]


In [7]:
b=arr.reshape(5,10)
b.shape
print(b)

[[43 28 56 19 29 90 14 81 57 44]
 [74 16 11  2 64 22 57 13 75 93]
 [ 7 93 36  5 24 11 99 46  3 23]
 [74 58 33 64 93 16 37 92 84 43]
 [20 33 53  6 46 27 76 83 31 67]]


In [9]:
flat=b.flatten()
print(flat.ndim)
flat

col_wise_flat=np.ravel(b,order='C')
print(col_wise_flat)

1
[43 28 56 19 29 90 14 81 57 44 74 16 11  2 64 22 57 13 75 93  7 93 36  5
 24 11 99 46  3 23 74 58 33 64 93 16 37 92 84 43 20 33 53  6 46 27 76 83
 31 67]


In [11]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(10,20,size=(2,3))
print(a)
print(b)

[[7 8 9]
 [6 2 4]]
[[12 11 16]
 [13 14 11]]


**concatenate**

In [12]:
con_row=np.concatenate((a,b),axis=0) #row wise
print(con_row)
con_col=np.concatenate((a,b),axis=1) #column wise
print(con_col)

[[ 7  8  9]
 [ 6  2  4]
 [12 11 16]
 [13 14 11]]
[[ 7  8  9 12 11 16]
 [ 6  2  4 13 14 11]]


In [16]:
x=np.random.randint(1,10,size=(2,2))
y=np.random.randint(30,40,size=(3,2))

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

r=np.concatenate((x,y),axis=0)
print(r)
#s=np.concatenate((x,y),axis=1)
#print(s)

[[ 6  2]
 [ 8  3]
 [39 38]
 [37 37]
 [30 33]]


In [19]:
m=np.random.randint(33,100,size=(1,5))
n=np.random.randint(100,200,size=(1,5))
print(m)
print(n)

transpose=m.T
print(transpose)

[[97 50 36 45 44]]
[[185 106 115 149 118]]
[[97]
 [50]
 [36]
 [45]
 [44]]


In [25]:
import numpy as np

m = np.random.randint(33, 100, size=(10,))
split_arr = np.array_split(m, 3)   # can split unevenly
print(split_arr)

spl_arr = np.split(m, 3)           # splits equally only
print(spl_arr)


[array([47, 47, 78, 60]), array([93, 47, 41]), array([48, 54, 75])]


ValueError: array split does not result in an equal division

In [30]:
x = np.array([10, 20, 40, 50])   # array 1
y = np.array([1, 2, 3, 4])       # array 2

add = x + y                      # addition
print("Addition:", add)

sub = x - y                      # subtraction
print("Subtraction:", sub)

mul = x * y                      # multiplication
print("Multiplication:", mul)

div = x / y                      # division
print("Division:", div)

remainder = x % y                # remainder
print("Remainder:", remainder)

arr1 = [10, 20, 30, 40, 50]      # list 1
arr2 = [5, 15, 25, 35, 45]       # list 2
a = arr1 + arr2                  # concatenation
print("List Concatenation:", a)


Addition: [11 22 43 54]
Subtraction: [ 9 18 37 46]
Multiplication: [ 10  40 120 200]
Division: [10.         10.         13.33333333 12.5       ]
Remainder: [0 0 1 2]
List Concatenation: [10, 20, 30, 40, 50, 5, 15, 25, 35, 45]
