<a href="https://colab.research.google.com/github/kaho0/Abstract/blob/main/Shore_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
arr=[1,2,3]
print(arr*5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [2]:
arr=[x*5 for x in arr]
print(arr)

[5, 10, 15]


In [15]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

# **Array Attributes**

In [17]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


In [18]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


In [19]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


***selecting a data type for an array***

In [26]:

arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)




arr = arr.astype(np.int32)
print(arr.dtype)


#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int64
int16


**nd array creation from existing data**

In [31]:
lst=[12,45,60.44,98,"tehe"]
arr=np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

['12' '45' '60.44' '98' 'tehe']
<class 'numpy.ndarray'>
<U32


In [32]:
tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [37]:
st={1,2,4}
# Convert the set to a list before creating the numpy array
arr = np.array(list(st),dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[1 2 4]
<class 'numpy.ndarray'>
int16
(3,)
1


In [41]:
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr1=np.array(list(values))
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

arrt=np.array(list(items))
print(arrt)
print(type(arrt))
print(arrt.dtype)
print(arrt.shape)
print(arrt.ndim)
print(arrt.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


**Creating ndarray from scratch**

In [42]:
arr=np.zeros((2,3),dtype=np.int16)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int16
(2, 3)
2
6


In [45]:
arr=np.ones_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(3, 2, 3)
3
18


In [48]:
arr=np.ones((4,3,2),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
<class 'numpy.ndarray'>
int8
(4, 3, 2)
3
24


In [49]:
arr=np.empty((4,3,2),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[-70  49]
  [ 54  40]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [-64   0]]

 [[  0   0]
  [  0   0]
  [  0   0]]]
<class 'numpy.ndarray'>
int8
(4, 3, 2)
3
24


In [57]:
arr=np.full((4,3,),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


In [59]:
arr=np.full_like((arr3),np.inf,dtype=np.float64)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
<class 'numpy.ndarray'>
float64
(3, 2, 3)
3
18


*array creation with random values*




In [60]:
arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.45528758 0.40992667 0.9815079 ]
 [0.98204744 0.96566177 0.74789479]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [62]:
 #np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (10,10))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[7 1 6 3 5 1 8 4 1 6]
 [5 4 8 1 5 9 5 1 4 2]
 [1 4 6 9 2 1 5 5 5 2]
 [5 1 5 2 9 9 5 3 2 6]
 [1 6 5 1 9 7 7 8 2 9]
 [5 3 9 7 4 9 2 4 9 3]
 [7 4 3 7 7 6 5 7 6 6]
 [9 2 8 2 3 3 6 9 7 5]
 [9 8 4 5 6 6 7 2 4 8]
 [9 4 4 3 6 4 8 4 4 3]]
<class 'numpy.ndarray'>
int64
(10, 10)
2
100


In [63]:
 #np.random.Uniform(start,end, shape)

arr = np.random.uniform(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[3.26254595 7.57925067 2.50154916]
 [1.24647106 3.1637193  5.03491482]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


**array creation with range functions**

In [67]:
arr=np.arange(1,10,1).reshape(3,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [73]:
arr=np.linspace(1,10,11)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [80]:
arr=np.logspace(0,4,6,base=2)
print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


**creating matrix for Linear algebra**

In [81]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [86]:

# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)

# np.eye(row , column,k)

mat = np.eye(3,4)
print(mat)
print("\n")
mat = np.eye(3,4,1)
print(mat)
print("\n")
mat = np.eye(3,4,-1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


**indexing and slicing**

In [87]:

#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[10 20 30]
[[1 2 3]
 [4 5 6]]
[[  1   2 100]
 [  4   5   6]]


In [90]:
arr1_mod = arr1[1:6:2].copy()
print(arr1_mod)

[2]


In [91]:
arr=np.array([1,2,3])
print(arr.ndim)

1


In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
arr=np.array([1,2.5,3])
print(arr.dtype)

float64


In [98]:
arr = np.array([[10,20,30],[40,50,60]])
arr[:,1]

array([20, 50])

In [100]:
arr = np.random.rand(2,3)
print(arr)

[[0.84700051 0.19859999 0.61834492]
 [0.37590644 0.31181959 0.47312527]]


In [101]:
arr=np.array([1,2,3,4,5])
arr[1:4]=0
print(arr)

[1 0 0 0 5]
